spring.application.name=proto-space

# DB接続（PostgreSQL）
spring.datasource.url=jdbc:postgresql://localhost:5432/protospace_development
spring.datasource.username=protospace
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true

# MyBatis（必要に応じて）
mybatis.configuration.map-underscore-to-camel-case=true
