spring.datasource.url=jdbc:postgresql://localhost:5432/protospace_development
spring.datasource.username=protospace
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver