spring.application.name=proto-space

# デフォルトはdev。環境変数SPRING_PROFILES_ACTIVEで上書き可能
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# 共通設定
spring.flyway.enabled=true
mybatis.configuration.map-underscore-to-camel-case=true
# server.forward-headers-strategy=framework